[project]
id = "artificial-theorems"
name = "ArtificialTheorems"
description = "AI/ML theoretical foundations: Robbins-Siegmund, SGD convergence, Value Iteration"
url = "https://github.com/GasStationManager/ArtificialTheorems"
commit = "b17d21e3568881aa7b2dd387793de3bff655a4da"
branch = "main"

[lean]
toolchain = "leanprover/lean4:v4.27.0"
mathlib_tag = "v4.27.0"

[[theorems]]
spec_module = "Registry.ArtificialTheorems.Opt.RobbinsSiegmund"
impl_module = "ArtificialTheorems.Opt.RobbinsSiegmund"
names = ["QLS.Stoch.robbinsSiegmund_expBound", "QLS.Stoch.robbinsSiegmund_full"]
permitted_axioms = ["propext", "Quot.sound", "Classical.choice"]

[[theorems]]
spec_module = "Registry.ArtificialTheorems.Opt.SGD"
impl_module = "ArtificialTheorems.Opt.SGD"
names = ["convergence_stochastic_gradient_method"]
permitted_axioms = ["propext", "Quot.sound", "Classical.choice"]

[[theorems]]
spec_module = "Registry.ArtificialTheorems.Opt.SGDUniqueMin"
impl_module = "ArtificialTheorems.Opt.SGDUniqueMin"
names = ["SGDUniqueMin.convergence_simplified"]
permitted_axioms = ["propext", "Quot.sound", "Classical.choice"]

[[theorems]]
spec_module = "Registry.ArtificialTheorems.RL.ValueIterationComplete"
impl_module = "ArtificialTheorems.RL.ValueIterationComplete"
names = ["VALUE_ITERATION_CONVERGENCE_COMPLETE"]
permitted_axioms = ["propext", "Quot.sound", "Classical.choice"]

[[theorems]]
spec_module = "Registry.ArtificialTheorems.RL.ApproxValueIterationInt"
impl_module = "ArtificialTheorems.RL.ApproxValueIterationInt"
names = ["ApproxValueIterationInt.INT_VALUE_ITERATION_APPROX", "ApproxValueIterationInt.INT_VALUE_ITERATION_EVENTUAL_BALL"]
permitted_axioms = ["propext", "Quot.sound", "Classical.choice"]

[build]
strategy = "copy"

[tools]
safe_verify_repo = "https://github.com/GasStationManager/SafeVerify"
safe_verify_ref = "v4.27.0"

[[signoffs]]
github_user = "GasStationManager"
spec_files = ["Registry/ArtificialTheorems/Opt/RobbinsSiegmund.lean"]
spec_version = "v1_mathlib-v4.27.0"
date = "2026-02-17"
issue = 1
status = "current"
spec_hash = "sha256:0ce62265367ec913a032e826b74a42c799e2d40c4f2fb3e7224a5b08316cb780"
comment = "S. Gadat, Lecture notes on Stochastic Optimization Algorithms, http://perso.math.univ-toulouse.fr/gadat/files/2012/12/cours_Algo_Stos_M2R5.pdf"
